[package]
name = "wwfypc-payments"
version = "0.1.0"
authors = ["Q 🦄 <q@magicalcodewit.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
diesel = { version = "1.4", features = ["postgres"] }
diesel-derive-enum = { version = "0.4", features = ["postgres"] }
diesel_migrations = "1.4"
dotenv = "0.9.0"
log = "0.4"
pretty_env_logger = "0.3"
tera = "0.11"
lazy_static = "1.4.0"
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.1"
http = "0.1"
listenfd = "0.3"
uuid = "0.7"
rust_decimal = "1.0"